name: buy_sell
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^4.2.2
  flutter_native_splash: ^2.4.2
  flutter_signin_button: ^2.0.0
  cupertino_icons: ^1.0.0
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  legacy_progress_dialog: ^0.1.2
  location: ^7.0.1
  geocoder_plus: ^0.0.1
  flutter_neumorphic_plus: ^3.4.0
  csc_picker: ^0.2.7
  convex_bottom_bar: ^3.2.0
  salomon_bottom_bar: ^3.3.2
  provider: ^6.1.2
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true




